### ISSUE TITLE
Specify a license

### ISSUE THREAD

**Issue by felixrabe** [rowland/go-fb#1]
Hi

I'm interested in building a minimal in-house (and maybe MIT @ GitHub) Firebird driver that just uses the embedded library (so/dll/dylib without server) that I can throw a DB file at ("SQLite mode") and then issue some simple SQL queries from Go code.

It would help if I knew to what extent I could use and/or contribute to this project's code.

**Comment by rowland** [comment]
I'm partial to liberal open source licenses like Apache 2 and MIT. This code is a port of the Ruby extension library fb, which I gave a complete overhaul many years ago and have maintained since then. It used the Ruby license. So, I don't know what affect that would have on the legalities, but it's all pretty liberal.

I welcome quality contributions, preferably accompanied by tests. There's another Go package for Firebird which conforms to the standard SQL interfaces and speaks the wire protocol without need for the native library. It looks promising, but perhaps not for the embedded scenario you're interested in.

This library has trouble with Unix signals thanks to interference from fb.so trying the handle them itself to perform some shutdown routines. So, that's a known issue.

**Comment by felixrabe** [comment]
Thanks. Can you give me a quick start on your test setup? Just running `go test github.com/rowland/go-fb` on OS X 10.9 gave me a lot of errors of this kind:

```
--- FAIL: TestExecute (0.31 seconds)
  connection_test.go:22: Unexpected error creating database: Unsuccessful execution caused by a system error that precludes successful execution of subsequent statements
    Your user name and password are not defined. Ask your database administrator to set up a Firebird login.
```

Also, from `connection.go` it looks like you tested building on OS X and Linux (other Unix as well?). Have you run go-fb on Windows as well?

**Comment by felixrabe** [comment]
Btw I had some preliminary success using go-fb in embedded mode, see https://github.com/felixrabe-go/go-fb. (I hereby explicitly grant you unlimited permission to use all my changes as you wish.)

```
go get gopkg.in/felixrabe-go/go-fb.v0
```

I haven't `go test`-ed it yet (see previous comment), and only tested on OS X with system-wide libraries.

My plan is to get this setup working on Windows 7 with bundled Firebird DLLs.

**Comment by rowland** [comment]
See database_test.go for connection strings with the expected credentials.

I have not attempted to build or run on Windows.

go test

Is all I use to run tests.

**Comment by AlekSi** [comment]
Can you please add a license?

**Comment by rowland** [comment]
Apache 2.
